import { useEffect, useMemo, useState } from "react";
import "./App.css";
const API=import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api/v1";
type Page="home"|"bloom"|"mood"|"diary"|"journey"|"plan"|"garden"|"support"|"privacy"|"reminders"|"achievements"|"circle"|"settings";
type Mood={id:number;mood:string;note?:string;stress?:number;energy?:number;created_at:string};
type Diary={id:number;title:string;content:string;mood?:string;created_at:string};
type Chat={role:string;content:string;risk_level:string;evidence?:string[]};
const moods=[['😔','Very low'],['🌧️','Low'],['😐','Okay'],['🙂','Good'],['🌸','Great']];
const activities=[{slug:'one_minute_reset',icon:'🫁',title:'60-second reset',text:'Slow the breath. Let the exhale be a little longer.'},{slug:'brain_dump',icon:'📝',title:'One-minute brain dump',text:'Write everything down without organizing it.'},{slug:'study_reset',icon:'📚',title:'15-minute study reset',text:'Choose one tiny study task. Only that.'}];
function App(){
 const [token,setToken]=useState(localStorage.getItem('mindbloom_token')||''); const [page,setPage]=useState<Page>('home'); const [auth,setAuth]=useState<'login'|'register'>('login'); const [email,setEmail]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState(''); const [user,setUser]=useState<any>(); const [moodData,setMoodData]=useState<Mood[]>([]); const [diaries,setDiaries]=useState<Diary[]>([]); const [insight,setInsight]=useState<any>(); const [chat,setChat]=useState<Chat[]>([]); const [draft,setDraft]=useState(''); const [listener,setListener]=useState(false); const [conversation,setConversation]=useState<number>(); const [loading,setLoading]=useState(false); const [lang,setLang]=useState('English'); const [diaryTitle,setDiaryTitle]=useState(''); const [diaryText,setDiaryText]=useState(''); const [toast,setToast]=useState('');
 const headers=()=>({"Content-Type":"application/json",Authorization:`Bearer ${token}`});
 async function api(path:string,opt:RequestInit={}){const r=await fetch(API+path,opt);if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.detail||'Something went wrong');}return r.status===204?null:r.json()}
 async function load(){if(!token)return;try{const [u,m,d,i,p]=await Promise.all([api('/auth/me',{headers:headers()}),api('/moods',{headers:headers()}),api('/diary',{headers:headers()}),api('/wellbeing/insights',{headers:headers()}),api('/preferences',{headers:headers()})]);setUser(u);setMoodData(m);setDiaries(d);setInsight(i);setLang(p.language||'English')}catch{logout()}}
 useEffect(()=>{load()},[token]);
 function logout(){localStorage.removeItem('mindbloom_token');setToken('');setUser(undefined)}
 async function authSubmit(e:React.FormEvent){e.preventDefault();setLoading(true);try{const d=await api(`/auth/${auth}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(auth==='register'?{email,username,password}:{email,password})});if(d.access_token){localStorage.setItem('mindbloom_token',d.access_token);setToken(d.access_token)}setMsg('')}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 async function checkMood(m:string){try{await api('/moods',{method:'POST',headers:headers(),body:JSON.stringify({mood:m})});setToast('Check-in saved 🌱');await load()}catch(e:any){setToast(e.message)}}
 async function saveDiary(e:React.FormEvent){e.preventDefault();try{await api('/diary',{method:'POST',headers:headers(),body:JSON.stringify({title:diaryTitle,content:diaryText})});setDiaryTitle('');setDiaryText('');setToast('Your private reflection is saved.');await load()}catch(e:any){setToast(e.message)}}
 async function sendBloom(){if(!draft.trim()||loading)return;const text=draft;setDraft('');setChat(c=>[...c,{role:'user',content:text,risk_level:'NORMAL'}]);setLoading(true);try{const d=await api('/bloom/chat',{method:'POST',headers:headers(),body:JSON.stringify({message:text,conversation_id:conversation,listener_mode:listener,language:lang})});setConversation(d.conversation_id);setChat(c=>[...c,{role:'assistant',content:d.message,risk_level:d.risk_level,evidence:d.evidence||[]}]);if(d.safety_escalation)setToast('Bloom has switched to the safety support path. 🛟')}catch(e:any){setChat(c=>[...c,{role:'assistant',content:e.message,risk_level:'NORMAL'}])}finally{setLoading(false)}}
 async function reflect(id:number){try{const d=await api('/bloom/reflection',{method:'POST',headers:headers(),body:JSON.stringify({diary_entry_id:id})});setToast('Reflection ready ✨');alert(d.reflection)}catch(e:any){setToast(e.message)}}
 const latest=useMemo(()=>moodData[0], [moodData]);
 if(!token)return <Auth auth={auth} setAuth={setAuth} email={email} setEmail={setEmail} username={username} setUsername={setUsername} password={password} setPassword={setPassword} submit={authSubmit} msg={msg} loading={loading} demo={async()=>{try{const d=await fetch(API+'/demo/session',{method:'POST'}).then(r=>r.json());localStorage.setItem('mindbloom_token',d.access_token);setToken(d.access_token)}catch(e:any){setMsg('Demo unavailable')}}}/>;
 return <div className="shell"><div className="orb orb1"/><div className="orb orb2"/><aside className="side"><div className="logo" onClick={()=>setPage('home')}><span>🌸</span><b>MindBloom</b></div><p className="tag">A safe place to bloom.</p><nav>{[['home','⌂','Home'],['bloom','✦','Talk to Bloom'],['mood','😊','Mood'],['diary','📖','Diary'],['journey','◌','Journey'],['plan','🌱','Bloom Plan'],['garden','🌸','Garden'],['reminders','⏰','Reminders'],['achievements','🏆','Achievements'],['circle','🌿','Bloom Circle'],['support','🫂','Support'],['privacy','🔐','Privacy']].map(([id,ic,l])=><button className={page===id?'nav active':'nav'} onClick={()=>setPage(id as Page)} key={id}><span>{ic}</span>{l}</button>)}</nav><div className="sidebottom"><button className="nav" onClick={()=>setPage('settings')}><span>⚙</span>Settings</button><button className="logout" onClick={logout}>Log out</button></div></aside><main className="main"><header><div><div className="eyebrow">MINDBLOOMAI · PRIVATE WELLBEING</div><h1>{pageTitle(page)}</h1></div><div className="profile">{user?.username?.slice(0,1).toUpperCase()}<span>{user?.username}</span></div></header><section className="content">{page==='home'&&<Home user={user} latest={latest} insight={insight} onMood={checkMood} go={setPage}/>} {page==='bloom'&&<Bloom chat={chat} draft={draft} setDraft={setDraft} send={sendBloom} loading={loading} listener={listener} setListener={setListener} lang={lang} setLang={setLang}/>} {page==='mood'&&<MoodPage moods={moodData} onMood={checkMood}/>} {page==='diary'&&<DiaryPage diaries={diaries} title={diaryTitle} setTitle={setDiaryTitle} text={diaryText} setText={setDiaryText} save={saveDiary} reflect={reflect}/>} {page==='journey'&&<Journey moods={moodData} insight={insight}/>} {page==='plan'&&<Plan onComplete={()=>setToast('Small step complete. Consistency, not perfection. 🌱')}/>} {page==='garden'&&<Garden/>} {page==='reminders'&&<Reminders/>} {page==='achievements'&&<Achievements/>} {page==='circle'&&<Circle/>} {page==='support'&&<Support/>} {page==='privacy'&&<Privacy/>} {page==='settings'&&<Settings lang={lang} setLang={setLang}/>}</section>{toast&&<button className="toast" onClick={()=>setToast('')}>{toast}</button>}</main></div>}
function pageTitle(p:Page){return ({home:'Your space to breathe',bloom:'Talk to Bloom',mood:'How are you feeling?',diary:'Your private diary',journey:'My wellbeing journey',plan:'My Bloom Plan',garden:'Your Bloom Garden',support:'Find support',privacy:'You are in control',settings:'Your preferences',reminders:'Gentle reminders',achievements:'Healthy milestones',circle:'Bloom Circle'} as any)[p]}
function Auth(p:any){return <div className="auth"><div className="auth-art"><div className="bloom-mark">🌸</div><div className="eyebrow">PRIVATE · EMPATHETIC · SAFETY-FIRST</div><h1>Your mind deserves<br/>a safe place to <i>bloom.</i></h1><p>Put what you're carrying into words. Understand the pattern. Take one small step.</p><div className="quote">“You don't have to have everything figured out today.”</div></div><form className="glass authform" onSubmit={p.submit}><div className="tabs"><button type="button" className={p.auth==='login'?'sel':''} onClick={()=>p.setAuth('login')}>Login</button><button type="button" className={p.auth==='register'?'sel':''} onClick={()=>p.setAuth('register')}>Create account</button></div>{p.auth==='register'&&<input placeholder="Your name" value={p.username} onChange={e=>p.setUsername(e.target.value)} required/>}<input type="email" placeholder="Email address" value={p.email} onChange={e=>p.setEmail(e.target.value)} required/><input type="password" placeholder="Password (8+ characters)" value={p.password} onChange={e=>p.setPassword(e.target.value)} required/><button type="button" className="demoBtn" onClick={p.demo}>Try the judge demo</button><button className="primary">{p.loading?'Opening your space…':p.auth==='login'?'Enter MindBloom':'Begin your journey'}</button>{p.msg&&<div className="error">{p.msg}</div>}<small>MindBloomAI is an AI wellbeing companion, not a therapist or medical service.</small></form></div>}
function Home({user,latest,insight,onMood,go}:any){return <><div className="welcome"><div><span className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</span><h2>Good evening, {user?.username} <span>🌙</span></h2><p>You don't have to have everything figured out today.</p></div><button className="primary small" onClick={()=>go('bloom')}>Talk to Bloom ✦</button></div><div className="grid2"><div className="glass moodcard"><div className="cardhead"><span>HOW ARE YOU FEELING?</span><b>Today</b></div><div className="moods">{moods.map(([e,l])=><button key={l} onClick={()=>onMood(l)}><span>{e}</span><small>{l}</small></button>)}</div><p className="muted">One check-in is enough. No score. No judgment.</p></div><div className="glass insight"><div className="icon">✦</div><div><span className="eyebrow">BLOOM NOTICED</span><h3>{insight?.insight||'A little attention to yourself can be a useful first step.'}</h3><p>Based only on information you choose to share.</p></div></div></div><div className="featureRow"><div className="glass feature bloomFeature" onClick={()=>go('bloom')}><div className="bubble">🫂</div><div><span className="eyebrow">TALK TO BLOOM</span><h3>Whatever you're carrying, you can start here.</h3><button className="textbtn">Open Bloom →</button></div></div><div className="glass snapshot"><span className="eyebrow">WELLBEING SNAPSHOT</span><div className="stats"><div><b>{latest?.mood||'—'}</b><span>Mood</span></div><div><b>{latest?.stress?`⚠ ${latest.stress}/5`:'—'}</b><span>Stress</span></div><div><b>{insight?.total_entries||0}</b><span>Check-ins</span></div></div></div></div><div className="gardenStrip glass" onClick={()=>go('garden')}><div className="gardenIcon">🌱</div><div><span className="eyebrow">YOUR BLOOM GARDEN</span><h3>Small steps help your garden grow.</h3><p>Consistency, not perfection.</p></div><span className="arrow">→</span></div></>}
function Bloom({chat,draft,setDraft,send,loading,listener,setListener,lang,setLang}:any){
 const [listening,setListening]=useState(false);
 function startVoice(){
  const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
  if(!SR){alert("Voice input is not available in this browser.");return}
  const r=new SR(); r.lang=lang==='Hindi'?'hi-IN':lang==='Kannada'?'kn-IN':'en-IN'; r.interimResults=false;
  r.onstart=()=>setListening(true); r.onend=()=>setListening(false); r.onerror=()=>setListening(false); r.onresult=(e:any)=>setDraft(e.results?.[0]?.[0]?.transcript||''); r.start();
 }
 function speak(text:string){if('speechSynthesis' in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text));}}
 return <div className="bloomPage">
  <div className="bloomHero"><div className="bloomAvatar">🌸</div><div><span className="eyebrow">BLOOM · AI WELLBEING COMPANION</span><h2>{listener?'I’m listening.':'Start wherever you are.'}</h2><p>{listener?'You can vent. I’ll focus on understanding before advice.':'Tell me what’s on your mind. We can take it one small step at a time.'}</p></div><div className="mode"><button className={listener?'on':''} onClick={()=>setListener(!listener)}>🫂 Listener Mode</button><select value={lang} onChange={e=>setLang(e.target.value)}><option>English</option><option>Hindi</option><option>Kannada</option></select></div></div>
  <div className="chat glass">
   {chat.length===0&&<div className="emptychat"><div>🌷</div><h3>Start wherever you are.</h3><p>Try “I’m overwhelmed about exams” or simply say what you’re feeling.</p></div>}
   {chat.map((m:Chat,i:number)=><div className={m.role==='user'?'bubble user':'bubble bloom'} key={i}><span>{m.role==='user'?'You':'Bloom'}</span><p>{m.content}</p>{m.role==='assistant'&&<><button className="speak" onClick={()=>speak(m.content)}>🔊 Listen</button>{m.evidence&&m.evidence.length>0&&<div className="evidence"><b>Why Bloom noticed</b><span>{m.evidence.join(' · ')}</span></div>}</>}{m.risk_level==='HIGH_RISK'&&<div className="safety">🛟 Please reach a real person and verified immediate support.</div>}</div>)}
   {loading&&<div className="typing">Bloom is thinking gently <i/> <i/> <i/></div>}
   <div className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={listener?'I just want to vent…':'What’s on your mind?'} rows={2}/><button className={listening?'send listening':'send'} onClick={startVoice}>{listening?'●':'🎙'}</button><button className="send" onClick={send}>↑</button></div>
   <div className="voiceNote">Voice input uses browser speech capabilities when available; it is not presented as Google Cloud Speech unless separately configured.</div>
  </div>
 </div>
}

function MoodPage({moods:m,onMood}:any){return <div className="stack"><div className="glass panel"><span className="eyebrow">CHECK IN</span><h2>How does today feel?</h2><div className="moods big">{moods.map(([e,l])=><button onClick={()=>onMood(l)} key={l}><span>{e}</span><small>{l}</small></button>)}</div></div><div className="glass panel"><span className="eyebrow">RECENT CHECK-INS</span>{m.slice(0,8).map((x:Mood)=><div className="row" key={x.id}><span>{x.mood}</span><small>{new Date(x.created_at).toLocaleDateString()}</small></div>)}</div></div>}
function DiaryPage(p:any){return <div className="diarygrid"><form className="glass panel" onSubmit={p.save}><span className="eyebrow">PRIVATE · ONLY YOU</span><h2>Put it into words.</h2><input placeholder="Give this reflection a title" value={p.title} onChange={e=>p.setTitle(e.target.value)} required/><textarea placeholder="Write freely. It doesn't need to be perfect." value={p.text} onChange={e=>p.setText(e.target.value)} rows={10} required/><button className="primary">Save reflection</button></form><div className="glass panel"><span className="eyebrow">YOUR REFLECTIONS</span>{p.diaries.length===0?<div className="empty"><div>📖</div><p>Your private pages will appear here.</p></div>:p.diaries.map((d:Diary)=><article className="entry" key={d.id}><div><small>{new Date(d.created_at).toLocaleDateString()}</small><h3>{d.title}</h3></div><p>{d.content.slice(0,180)}{d.content.length>180?'…':''}</p><button className="textbtn" onClick={()=>p.reflect(d.id)}>Reflect with Bloom ✦</button></article>)}</div></div>}
function Journey({moods,insight}:any){const [week,setWeek]=useState<any>();useEffect(()=>{const t=localStorage.getItem('mindbloom_token')||'';fetch(API+'/wellbeing/weekly-reflection',{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.json()).then(setWeek)},[]);return <div className="stack"><div className="glass panel"><span className="eyebrow">OBSERVABLE PATTERNS</span><h2>A pattern worth noticing.</h2><p>{insight?.insight||'Keep checking in so Bloom has enough user-provided information to notice patterns.'}</p><div className="timeline">{moods.slice(0,10).reverse().map((m:Mood)=><div key={m.id}><span>{m.mood}</span><i/></div>)}</div></div><div className="glass panel"><span className="eyebrow">YOUR WEEK WITH BLOOM · {week?.provider||'preparing'}</span><h3>Reflection, not diagnosis.</h3><p className="preline">{week?.reflection||'Your weekly reflection will appear here after your first week of data.'}</p></div></div>}

function Plan({onComplete}:any){const [done,setDone]=useState<string[]>([]);async function complete(slug:string){const token=localStorage.getItem('mindbloom_token')||'';const r=await fetch(API+'/recommendations',{headers:{Authorization:`Bearer ${token}`}});const all=await r.json();const a=all.find((x:any)=>x.slug===slug);if(a){await fetch(API+`/activities/${a.id}/complete`,{method:'POST',headers:{Authorization:`Bearer ${token}`}})}setDone(x=>[...x,slug]);onComplete()}return <div className="stack"><div className="glass panel plan"><span className="eyebrow">TODAY'S BLOOM PLAN</span><h2>Let's make today smaller.</h2>{activities.map((a,i)=><div className="planitem" key={a.slug}><span>{a.icon}</span><div><b>{a.title}</b><p>{a.text}</p></div><button onClick={()=>complete(a.slug)} disabled={done.includes(a.slug)}>{done.includes(a.slug)?'Done ✓':i===0?'Start':'Do this'}</button></div>)}</div></div>}

function Garden(){const [g,setG]=useState<any>();useEffect(()=>{const t=localStorage.getItem('mindbloom_token');fetch(API+'/gamification/garden',{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.json()).then(setG)},[]);return <div className="gardenPage glass panel"><div className="gardenScene"><div className="sun">☀</div><div className="plant">🌱</div><div className="ground">🌿 🌷 🌿 🌸 🌿</div></div><span className="eyebrow">YOUR BLOOM GARDEN</span><h2>Growing gently.</h2><p>{g?.message||'Small wellbeing actions become visible growth.'}</p><div className="progress"><span style={{width:`${g?.growth||20}%`}}/></div><div className="gardenStats"><b>{g?.points||0}<small>points</small></b><b>Level {g?.level||1}<small>growth</small></b></div></div>}
function Reminders(){const [items,setItems]=useState<any[]>([]);const [title,setTitle]=useState('');const [time,setTime]=useState('');const token=localStorage.getItem('mindbloom_token')||'';async function load(){const r=await fetch(API+'/reminders',{headers:{Authorization:`Bearer ${token}`}});setItems(await r.json())}useEffect(()=>{load()},[]);async function add(e:any){e.preventDefault();await fetch(API+'/reminders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({title,message:'A gentle moment for yourself.',reminder_time:new Date(time).toISOString()})});setTitle('');setTime('');load()}return <div className="diarygrid"><form className="glass panel" onSubmit={add}><span className="eyebrow">NO GUILT · NO STREAKS</span><h2>Would you like a gentle reminder?</h2><input placeholder="Reminder title" value={title} onChange={e=>setTitle(e.target.value)} required/><input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} required/><button className="primary">Add reminder</button></form><div className="glass panel"><span className="eyebrow">YOUR REMINDERS</span>{items.length===0?<div className="empty"><div>⏰</div><p>No reminders yet.</p></div>:items.map(x=><div className="row" key={x.id}><span>{x.title}</span><small>{new Date(x.reminder_time).toLocaleString()}</small></div>)}</div></div>}
function Achievements(){const [data,setData]=useState<any>();useEffect(()=>{const t=localStorage.getItem('mindbloom_token')||'';fetch(API+'/gamification',{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.json()).then(setData)},[]);return <div className="stack"><div className="glass panel"><span className="eyebrow">HEALTHY MILESTONES</span><h2>Celebrate the steps that matter.</h2><p>Achievements reward healthy actions, not endless app usage.</p><div className="achievementGrid">{(data?.achievements||[]).map((a:any)=><div className="achievement" key={a.id}>🌸<b>{a.name}</b><small>{a.description}</small></div>)}</div></div><div className="glass panel"><span className="eyebrow">YOUR PROGRESS</span><h3>{data?.profile?.points||0} points · Level {data?.profile?.level||1}</h3><p>Consistency, not perfection.</p></div></div>}

function Circle(){const [posts,setPosts]=useState([{id:1,text:'Everyone around me seems successful, and I feel like I am falling behind.',likes:12},{id:2,text:'Taking one small step today helped more than trying to solve everything at once.',likes:19}]);return <div className="stack"><div className="glass panel"><span className="eyebrow">CONTROLLED PEER SUPPORT · PROTOTYPE</span><h2>You are not the only one.</h2><p>Anonymous supportive reflections. No private contact exchange. Report harmful content. This prototype is intentionally moderated and limited.</p></div>{posts.map(p=><article className="glass panel circlePost" key={p.id}><span>Anonymous 🌱</span><p>“{p.text}”</p><div><button className="secondary" onClick={()=>setPosts(ps=>ps.map(x=>x.id===p.id?{...x,likes:x.likes+1}:x))}>💚 I relate · {p.likes}</button><button className="textbtn">Report</button></div></article>)}</div>}

function Support(){return <div className="stack"><div className="glass safetyCard"><span>🛟</span><div><h2>If things feel serious</h2><p>You deserve support from a real person. MindBloom does not contact anyone automatically or pretend to be emergency care.</p><b>For immediate danger, use your local emergency service or nearest emergency department.</b></div></div><div className="grid2"><div className="glass panel"><span className="eyebrow">MY SUPPORT CIRCLE</span><h2>People I trust.</h2><p>Add a parent, sibling, friend, mentor or trusted adult in the connected app.</p><button className="secondary">Add trusted person</button></div><div className="glass panel"><span className="eyebrow">VERIFIED RESOURCES</span><h2>Find the right door.</h2><p>Provider directories require current verification. MindBloom never fabricates listings or crisis numbers.</p><button className="secondary">Open support resources</button></div></div></div>}
function Privacy(){return <div className="grid2"><div className="glass panel"><span className="eyebrow">MY PRIVACY</span><h2>You are in control.</h2>{['What data is stored','What Bloom can access','What Bloom remembers','Export my data','Delete conversations','Delete my account'].map(x=><div className="privacyRow" key={x}><span>{x}</span><b>›</b></div>)}</div><div className="glass panel"><span className="eyebrow">AI MEMORY</span><div className="memoryIcon">🧠</div><h3>Memory is optional.</h3><p>Bloom should only keep appropriate, user-approved context. You can view and delete memory.</p><button className="secondary">Manage memory</button></div></div>}
function Settings({lang,setLang}:any){return <div className="glass panel settings"><span className="eyebrow">PREFERENCES</span><h2>Make Bloom feel like your space.</h2><label>Preferred language<select value={lang} onChange={e=>setLang(e.target.value)}><option>English</option><option>Hindi</option><option>Kannada</option></select></label><label>AI memory<div className="toggle on">ON <span/></div></label><label>Gentle reminders<div className="toggle on">ON <span/></div></label><p className="muted">Voice Mode uses browser capabilities when configured; it is never presented as Google Cloud Speech unless that service is actually configured.</p></div>}
export default App;
